apiVersion: apps/v1
kind: Deployment

metadata:
  name: fastapi-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: fastapi

  template:
    metadata:
      labels:
        app: fastapi

    spec:
      containers:
        - name: fastapi

          image: aniket24122000/fastapi-demo:v3

          command: ["uvicorn"]

          args:
            - "main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"

          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:
              path: /wrong-live
              port: 8000

            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

---
apiVersion: v1
kind: Service

metadata:
  name: fastapi-service

spec:
  type: NodePort

  selector:
    app: fastapi

  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080